#!/usr/bin/env bash
LC_ALL=C

function usage() {
  echo -e "Usage

deb-get {update | upgrade | show pkg | install pkg | reinstall pkg | remove pkg
| purge pkg | search pkg | cache | clean | list | prettylist | help | version}

deb-get provides a high-level commandline interface for the package management
system to easily install and update packages published in 3rd party apt
repositories or via direct download.

update\n\tupdate is used to resynchronize the package index files from their sources.\n
upgrade\n\tupgrade is used to install the newest versions of all packages currently installed on the system.\n
install\n\tinstall is followed by one package desired for installation or upgrading.\n
reinstall\n\treinstall is followed by one package desired for reinstallation.\n
remove\n\tremove is identical to install except that packages are removed instead of installed.\n
purge\n\tpurge is identical to remove except that packages are removed and purged (any configuration files are deleted too).\n
clean\n\tclean clears out the local repository (/var/cache/deb-get) of retrieved package files.\n
search\n\tsearch for the given regex(7) term(s) from the list of available packages supported by deb-get and display matches.\n
show\n\tshow information about the given package including its install source and update mechanism.\n
list\n\tlist the packages available via deb-get.\n
prettylist\n\tmarkdown formatted list the packages available via deb-get. Use this to update README.md\n
cache\n\tlist the contents of the deb-get cache (/var/cache/deb-get)\n
"
  exit 1
}

function unroll_url() {
    curl -w "%{url_effective}\n" -I -L -s -S "${1}" -o /dev/null
}

function get_github_releases() {
    METHOD="github"
    # Cache github releases json for 1 hour to try and prevent API rate limits
    #   https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
    #   {"message":"API rate limit exceeded for 62.31.16.154. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
    #   curl -I https://api.github.com/users/flexiondotorg

    # Do not process github releases while generating a pretty list
    if [ "${PRETTY}" -eq 0 ]; then
        fancy_message info "Updating ${CACHE_DIR}/${APP}.json"
        if [ ! -e "${CACHE_DIR}/${APP}.json" ] || test "$(find "${CACHE_DIR}/${APP}.json" -mmin +60)"; then
            if ! wget -q "${1}" -O "${CACHE_DIR}/${APP}.json"; then
                fancy_message warn "Updating ${CACHE_DIR}/${APP}.json failed. Deleting it."
                rm "${CACHE_DIR}/${APP}.json" 2>/dev/null
            fi
            if [ -f "${CACHE_DIR}/${APP}.json" ] && grep "API rate limit exceeded" "${CACHE_DIR}/${APP}.json"; then
                fancy_message warn "Updating ${CACHE_DIR}/${APP}.json exceed GitHub API limits. Deleting it."
                rm "${CACHE_DIR}/${APP}.json" 2>/dev/null
            fi
        fi
    fi
}

function fancy_message() {
    if [ -z "${1}" ] || [ -z "${2}" ]; then
      return
    fi

    local RED="\e[31m"
    local GREEN="\e[32m"
    local YELLOW="\e[33m"
    local RESET="\e[0m"
    local MESSAGE_TYPE=""
    local MESSAGE=""
    MESSAGE_TYPE="${1}"
    MESSAGE="${2}"

    case ${MESSAGE_TYPE} in
      info) echo -e "  [${GREEN}+${RESET}] ${MESSAGE}";;
      progress) echo -en "  [${GREEN}+${RESET}] ${MESSAGE}";;
      warn) echo -e "  [${YELLOW}*${RESET}] WARNING! ${MESSAGE}";;
      error) echo -e "  [${RED}!${RESET}] ERROR! ${MESSAGE}";;
      fatal) echo -e "  [${RED}!${RESET}] ERROR! ${MESSAGE}"
             exit 1;;
      *) echo -e "  [?] UNKNOWN: ${MESSAGE}";;
    esac
}

function download_deb() {
    local URL="${1}"
    local FILE="${URL##*/}"

    if ! wget --quiet --continue --show-progress --progress=bar:force:noscroll "${URL}" -O "${CACHE_DIR}/${FILE}"; then
        fancy_message error "Failed to download ${URL}. Deleting ${CACHE_DIR}/${FILE}..."
        rm "${CACHE_DIR}/${FILE}" 2>/dev/null
    fi
}

function eula() {
    if [ -n "${EULA}" ]; then
        echo -e "${EULA}"
        echo -e "\nDo you agree to the ${APP} EULA?"
        select yn in "Yes" "No"; do
            case $yn in
                Yes) break;;
                No) exit;;
            esac
        done
    fi
}

function update_apt() {
    apt-get -q -y update
}

function upgrade_apt() {
    apt-get -q -y upgrade
}

function install_apt() {
    if [ -n "${APT_KEY_URL}" ]; then
        wget -q "${APT_KEY_URL}" -O "/etc/apt/trusted.gpg.d/${APT_LIST_NAME}.asc"
    fi

    if [ -n "${GPG_KEY_URL}" ]; then
        if [ ! -d /usr/share/keyrings ]; then
            mkdir -p /usr/share/keyrings 2>/dev/null
        fi
        wget -q "${GPG_KEY_URL}" -O "/usr/share/keyrings/${APT_LIST_NAME}-archive-keyring.gpg"
    fi

    #TODO: https://superuser.com/questions/1641291/gpg-only-download-a-key-from-a-keyserver

    echo -e "${APT_REPO_URL}" > "/etc/apt/sources.list.d/${APT_LIST_NAME}.list"
    update_apt

    if ! dpkg -l "${APP}" >/dev/null 2>&1; then
        eula
        apt-get -q -y install "${APP}"
    else
        STATUS="$(dpkg -s "${APP}" | grep ^Status: | cut -d" " -f2-)"
        if [ "${STATUS}" == "install ok installed" ] && [ "${ACTION}" == "reinstall" ]; then
            apt-get -q -y --reinstall install "${APP}"
        else
            fancy_message info "${APP} is up to date."
        fi
    fi
}

function install_ppa() {
    if apt-add-repository -y --no-update "${PPA}"; then
        update_apt
        if ! dpkg -l "${APP}" >/dev/null 2>&1; then
            eula
            apt-get -q -y install "${APP}"
        else
            STATUS="$(dpkg -s "${APP}" | grep ^Status: | cut -d" " -f2-)"
            if [ "${STATUS}" == "install ok installed" ] && [ "${ACTION}" == "reinstall" ]; then
                apt-get -q -y --reinstall install "${APP}"
            else
                fancy_message info "${APP} is up to date."
            fi
        fi
    else
        fancy_message error "Failed to add: ${PPA}. Deleting it."
        apt-add-repository -y --remove "${PPA}"
    fi
}

function install_deb() {
    local URL="${1}"
    local FILE="${URL##*/}"
    local STATUS=""

    if [ -z "${URL}" ]; then
        fancy_message error "Download URL is empty. Skipping."
        return
    fi

    if ! dpkg -l "${APP}" >/dev/null 2>&1; then
        eula
        download_deb "${URL}"
        apt-get -q -y install "${CACHE_DIR}/${FILE}"
    else
        STATUS="$(dpkg -s "${APP}" | grep ^Status: | cut -d" " -f2-)"
        if [ "${STATUS}" == "install ok installed" ] && [ "${ACTION}" == "reinstall" ]; then
            download_deb "${URL}"
            apt-get -q -y --reinstall install "${CACHE_DIR}/${FILE}"
        elif dpkg --compare-versions "${VERSION_PUBLISHED}" gt "${VERSION_INSTALLED}"; then
            download_deb "${URL}"
            apt-get -q -y install "${CACHE_DIR}/${FILE}"
        else
            fancy_message info "${FILE} is up to date."
        fi
    fi
    if [ -f "${CACHE_DIR}/${FILE}" ]; then
        rm "${CACHE_DIR}/${FILE}" 2>/dev/null
    fi
}

function remove_deb() {
    local APP="${1}"
    local REMOVE="${2:-remove}"
    local FILE="${URL##*/}"
    local STATUS=""

    if dpkg -l "${APP}" >/dev/null 2>&1; then
        STATUS="$(dpkg -s "${APP}" | grep ^Status: | cut -d" " -f2-)"
        if [ "${STATUS}" == "deinstall ok config-files" ]; then
            REMOVE="purge"
        fi
        apt-get -q -y --autoremove ${REMOVE} "${APP}"

        case ${METHOD} in
            direct|github|website)
                if [ -f "${CACHE_DIR}/${FILE}" ]; then
                    rm "${CACHE_DIR}/${FILE}" 2>/dev/null
                fi
                ;;
            apt)
                if [ -n "${APT_KEY_URL}" ]; then
                    rm "/etc/apt/trusted.gpg.d/${APT_LIST_NAME}.asc" 2>/dev/null
                fi
                if [ -n "${GPG_KEY_URL}" ]; then
                    rm "/usr/share/keyrings/${APT_LIST_NAME}-archive-keyring.gpg" 2>/dev/null
                fi
                if [ -n "${APT_LIST_NAME}" ] && [ -f "/etc/apt/sources.list.d/${APT_LIST_NAME}.list" ]; then
                    rm "/etc/apt/sources.list.d/${APT_LIST_NAME}.list"
                    update_apt
                fi
                ;;
            ppa)
                rm "${CACHE_DIR}/${APP}"*.deb 2>/dev/null
                if [ -n "${PPA}" ]; then
                    apt-add-repository -y --remove "${PPA}"
                    update_apt
                fi
                ;;
        esac
    else
        fancy_message info "${APP} is not installed."
    fi
}

function version_deb() {
    if dpkg -l "${APP}" >/dev/null 2>&1; then
        echo "$(dpkg -s "${APP}" | grep ^Version: | cut -d' ' -f2)"
    else
        echo ""
    fi
}

function info_deb() {
    local INSTALLED="${VERSION_INSTALLED:-No}"
    case ${METHOD} in
        direct|github|website) echo -e "${PRETTY_NAME}\n  Package:\t${APP}\n  Updater:\tdeb-get\n  Installed:\t${INSTALLED}\n  Published:\t${VERSION_PUBLISHED}\n  Architecture:\t${ARCHS_SUPPORTED}\n  Download:\t${URL}\n  Website:\t${WEBSITE}";;
        apt) echo -e "${PRETTY_NAME}\n  Package:\t${APP}\n  Updater:\tapt\n  Installed:\t${INSTALLED}\n  Architecture:\t${ARCHS_SUPPORTED}\n  Repository:\t${APT_REPO_URL}\n  Website:\t${WEBSITE}";;
        ppa) echo -e "${PRETTY_NAME}\n  Package:\t${APP}\n  Updater:\tapt\n  Installed:\t${INSTALLED}\n  Architecture:\t${ARCHS_SUPPORTED}\n  Launchpad:\t${PPA}\n  Website:\t${WEBSITE}";;
    esac
}

function validate_deb() {
    export APP="${1}"
    export PRETTY="${2:-0}"

    if [[ ! " ${APPS[*]} " =~ " ${APP} " ]]; then
        fancy_message error "${APP} is not a supported application."
        list_debs
        exit 1
    fi

    export APT_KEY_URL=""
    export GPG_KEY_URL=""
    export APT_LIST_NAME=""
    export APT_REPO_URL=""
    export PPA=""
    export ARCHS_SUPPORTED="amd64"
    export METHOD="website"
    export EULA=""
    export URL=""
    export VERSION_INSTALLED=""
    export VERSION_PUBLISHED=""
    export PRETTY_NAME=""
    export WEBSITE=""

    # Source the variables
    deb_${APP}
    VERSION_INSTALLED=$(version_deb)
    if [ -n "${APT_REPO_URL}" ]; then
        METHOD="apt"
    elif  [ -n "${PPA}" ]; then
        METHOD="ppa"
    fi
}

function list_debs() {
    local PAD='                              '
    for DEB in "${APPS[@]}"; do
        if dpkg -l "${DEB}" >/dev/null 2>&1; then
            STATUS="$(dpkg -s "${DEB}" | grep ^Status: | cut -d" " -f4- )"
            printf "%s %s [ ${STATUS} ]\n" "${DEB}" "${PAD:${#DEB}}"
        else
            echo "${DEB}"
        fi
    done
}

function prettylist_debs() {
    local ICON=""
    for DEB in "${APPS[@]}"; do
        validate_deb "${DEB}" 1
        case ${METHOD} in
            apt)    ICON="debian.png";;
            github) ICON="github.png";;
            ppa)    ICON="launchpad.png";;
            *)      ICON="direct.png";;
        esac
        echo "<img src=\".github/${ICON}\" align=\"top\" width=\"20\" /> [${PRETTY_NAME}](${WEBSITE}) ("'`'"${DEB}"'`'")<br />"
    done
}

function update_debs() {
    local STATUS=""
    update_apt
    for DEB in "${APPS[@]}"; do
        validate_deb "${DEB}"
        # Only download .debs that are installed
        if dpkg -l "${DEB}" >/dev/null 2>&1; then
            STATUS="$(dpkg -s "${DEB}" | grep ^Status: | cut -d" " -f2-)"
            if [ "${METHOD}" == "direct" ] || [ "${METHOD}" == "github" ] || [ "${METHOD}" == "website" ]; then
                if [ "${STATUS}" == "install ok installed" ] && dpkg --compare-versions "${VERSION_PUBLISHED}" gt "${VERSION_INSTALLED}"; then
                    fancy_message warn "${APP} (${VERSION_INSTALLED}) has an update pending for: ${VERSION_PUBLISHED}"
                fi
            fi
        fi
    done
}

function upgrade_debs() {
    local STATUS=""
    upgrade_apt
    for DEB in "${APPS[@]}"; do
        validate_deb "${DEB}"
        # Only upgrade .debs that are installed
        if dpkg -l "${DEB}" >/dev/null 2>&1; then
            STATUS="$(dpkg -s "${DEB}" | grep ^Status: | cut -d" " -f2-)"
            if [ "${METHOD}" == "direct" ] || [ "${METHOD}" == "github" ] || [ "${METHOD}" == "website" ]; then
                if [ "${STATUS}" == "install ok installed" ]; then
                    install_deb "${URL}"
                fi
            fi
        fi
    done
}

function deb_discord() {
    URL=$(unroll_url "https://discord.com/api/download?platform=linux&format=deb")
    VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f6)"
    PRETTY_NAME="Discord"
    WEBSITE="https://discord.com/"
}

function deb_quickemu() {
    PPA="ppa:flexiondotorg/quickemu"
    PRETTY_NAME="Quickemu"
    WEBSITE="https://github.com/quickemu-project/quickemu"
}

function deb_firefox-esr() {
    PPA="ppa:mozillateam/ppa"
    PRETTY_NAME="Firefox ESR"
    WEBSITE="https://www.mozilla.org/firefox/enterprise/"
}

function deb_quickgui() {
    PPA="ppa:yannick-mauray/quickgui"
    PRETTY_NAME="Quickgui"
    WEBSITE="https://github.com/quickemu-project/quickgui"
}

function deb_nextcloud-desktop() {
    PPA="ppa:nextcloud-devs/client"
    PRETTY_NAME="Nextcloud Desktop"
    WEBSITE="https://nextcloud.com/"
}

function deb_keypassxc() {
    PPA="ppa:phoerious/keepassxc"
    PRETTY_NAME="KeyPassXC"
    WEBSITE="https://keepassxc.org/"
}

function deb_ubuntu-make() {
    PPA="ppa:lyzardking/ubuntu-make"
    PRETTY_NAME="Ubuntu-Make"
    WEBSITE="https://github.com/ubuntu/ubuntu-make"
}

function deb_atom() {
    APT_KEY_URL="https://packagecloud.io/AtomEditor/atom/gpgkey"
    APT_LIST_NAME="atom"
    APT_REPO_URL="deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"
    PRETTY_NAME="Atom"
    WEBSITE="https://atom.io/"
}

function deb_code() {
    APT_KEY_URL="https://packages.microsoft.com/keys/microsoft.asc"
    APT_LIST_NAME="vscode"
    APT_REPO_URL="deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    PRETTY_NAME="Visual Studio Code"
    WEBSITE="https://code.visualstudio.com/"
}

function deb_rstudio() {
    URL="$(curl -s "https://www.rstudio.com/products/rstudio/download/" | grep "amd64.deb" | grep -v "tar.gz" | head -n1 | cut -d'"' -f2)"
    VERSION_PUBLISHED="$(echo "${URL}" | cut -d'-' -f2-3 | sed s'/-/+/')"
    PRETTY_NAME="RStudio"
    WEBSITE="https://www.rstudio.com/"
}

function deb_beersmith3() {
    URL="$(curl -s "https://beersmith.com/download-beersmith/" | grep "amd64.deb" | head -n1 | cut -d'"' -f2)"
    VERSION_PUBLISHED="$(echo "${URL}" | cut -d'-' -f3 | cut -d'_' -f1)"
    PRETTY_NAME="BeerSmith"
    WEBSITE="https://beersmith.com/"
}

function deb_ocenaudio() {
    ARCHS_SUPPORTED="amd64 i386"
    VERSION_PUBLISHED="$(curl -s "https://www.ocenaudio.com/en/download" | grep "<p>Version" | head -n1 | sed -e 's/<[^>]*>//g' | cut -d' ' -f2)"
    case ${HOST_ARCH} in
        amd64) URL="https://www.ocenaudio.com/downloads/index.php/ocenaudio_debian9_64.deb";;
        i386) URL="https://www.ocenaudio.com/downloads/index.php/ocenaudio_debian9_32.deb";;
    esac
    PRETTY_NAME="ocenaudio"
    WEBSITE="https://www.ocenaudio.com/"
}

function deb_github-desktop() {
    get_github_releases "https://api.github.com/repos/shiftkey/desktop/releases/latest"
    VERSION_PUBLISHED="$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|release-||')"
    URL=$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="GitHub Desktop"
    WEBSITE="https://desktop.github.com/"
}

function deb_lsd() {
    ARCHS_SUPPORTED="amd64 arm64"
    get_github_releases "https://api.github.com/repos/Peltoche/lsd/releases/latest"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v musl | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v musl | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="LSDeluxe"
    WEBSITE="https://github.com/Peltoche/lsd"
}

function deb_bat() {
    ARCHS_SUPPORTED="amd64 arm64 armhf"
    get_github_releases "https://api.github.com/repos/sharkdp/bat/releases/latest"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v musl | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v musl | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="bat"
    WEBSITE="https://github.com/sharkdp/bat"
}

function deb_git-delta() {
    ARCHS_SUPPORTED="amd64 arm64 armhf i386"
    get_github_releases "https://api.github.com/repos/dandavison/delta/releases/latest"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v musl | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v musl | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="git-delta"
    WEBSITE="https://github.com/dandavison/delta"
}

function deb_fd() {
    ARCHS_SUPPORTED="amd64 arm64 armhf"
    get_github_releases "https://api.github.com/repos/sharkdp/fd/releases/latest"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v musl | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v musl | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="fd"
    WEBSITE="https://github.com/sharkdp/fd"
}

function deb_duf() {
    ARCHS_SUPPORTED="amd64 arm64 armhf"
    get_github_releases "https://api.github.com/repos/muesli/duf/releases/latest"
    case "${HOST_ARCH}" in
        armhf) VERSION_PUBLISHED="$(grep "browser_download_url.*armv7.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
               URL=$(grep "browser_download_url.*armv7.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
               ;;
        *)     VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
               URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
               ;;
    esac
    PRETTY_NAME="duf"
    WEBSITE="https://github.com/muesli/duf"
}

function deb_zenith() {
    get_github_releases "https://api.github.com/repos/bvaisvil/zenith/releases/latest"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Zenith"
    WEBSITE="https://github.com/bvaisvil/zenith"
}

function deb_rclone() {
    ARCHS_SUPPORTED="amd64 arm64 armhf i386"
    get_github_releases "https://api.github.com/repos/rclone/rclone/releases/latest"
    case ${HOST_ARCH} in
        armhf)
            VERSION_PUBLISHED="$(grep "browser_download_url.*arm-v7.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
            URL=$(grep "browser_download_url.*arm-v7.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
            ;;
        i386)
            VERSION_PUBLISHED="$(grep "browser_download_url.*386.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
            URL=$(grep "browser_download_url.*386.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
            ;;
        *)
            VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
            URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
            ;;
    esac
    PRETTY_NAME="Rclone"
    WEBSITE="https://rclone.org/"
}

function deb_simplenote() {
    ARCHS_SUPPORTED="amd64 armhf i386"
    get_github_releases "https://api.github.com/repos/Automattic/simplenote-electron/releases/latest"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
    case ${HOST_ARCH} in
        amd64|i386) URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4);;
        armhf) URL=$(grep "browser_download_url.*armhv7l.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4);;
    esac
    PRETTY_NAME="Simplenote"
    WEBSITE="https://simplenote.com/"
}

function deb_element-desktop() {
    GPG_KEY_URL="https://packages.element.io/debian/element-io-archive-keyring.gpg"
    APT_LIST_NAME="element-io"
    APT_REPO_URL="deb [signed-by=/usr/share/keyrings/${APT_LIST_NAME}-archive-keyring.gpg] https://packages.element.io/debian/ default main"
    PRETTY_NAME="Element"
    WEBSITE="https://element.io/"
}

function deb_1password() {
    APT_KEY_URL="https://downloads.1password.com/linux/keys/1password.asc"
    APT_LIST_NAME="1password"
    APT_REPO_URL="deb [arch=amd64] https://downloads.1password.com/linux/debian/amd64 stable main"
    PRETTY_NAME="1Password"
    WEBSITE="https://1password.com/"
}

function deb_weechat() {
    GPG_KEY_URL="https://weechat.org/dev/info/debian_repository_signing_key/"
    APT_LIST_NAME="weechat"
    APT_REPO_URL="deb [signed-by=/usr/share/keyrings/${APT_LIST_NAME}-archive-keyring.gpg] https://weechat.org/ubuntu ${UBUNTU_CODENAME} main"
    PRETTY_NAME="WeeChat"
    WEBSITE="https://weechat.org/"
}

function deb_jami() {
    GPG_KEY_URL="https://dl.jami.net/public-key.gpg"
    APT_LIST_NAME="jami"
    APT_REPO_URL="deb [signed-by=/usr/share/keyrings/${APT_LIST_NAME}-archive-keyring.gpg] https://dl.jami.net/nightly/ubuntu_${UBUNTU_RELEASE}/ jami main"
    PRETTY_NAME="Jami"
    WEBSITE="https://jami.net/"
}

function deb_google-chrome-stable() {
    APT_KEY_URL="http://dl.google.com/linux/linux_signing_key.pub"
    APT_LIST_NAME="google-chrome"
    APT_REPO_URL="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    EULA="By downloading Chrome, you agree to the Google Terms of Service and Chrome and Chrome OS Additional Terms of Service\n - https://policies.google.com/terms\n - https://www.google.co.uk/intl/en/chrome/terms/"
    PRETTY_NAME="Google Chrome"
    WEBSITE="https://www.google.com/chrome/"
}

function disabled_ungoogled-chromium() {
    APT_LIST_NAME="home-ungoogled_chromium.list"
    case "${UBUNTU_CODENAME}" in
        focal)
            APT_KEY_URL="https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/Release.key"
            APT_REPO_URL="deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/ /"
            ;;
        *)
            APT_KEY_URL="https://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Sid/Release.key"
            APT_REPO_URL="deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Sid/ /"
            ;;
    esac
    PRETTY_NAME="ungoogled-chromium"
    WEBSITE="https://github.com/Eloston/ungoogled-chromium"
}

function deb_opera-stable() {
    APT_KEY_URL="https://deb.opera.com/archive.key"
    APT_LIST_NAME="opera-stable"
    APT_REPO_URL="deb https://deb.opera.com/opera-stable/ stable non-free"
    PRETTY_NAME="Opera"
    WEBSITE="https://www.opera.com/"
}

function deb_teams() {
    APT_KEY_URL="https://packages.microsoft.com/keys/microsoft.asc"
    APT_LIST_NAME="teams"
    APT_REPO_URL="deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"
    PRETTY_NAME="Microsoft Teams"
    WEBSITE="https://www.microsoft.com/microsoft-teams/group-chat-software"
}

function deb_enpass() {
    APT_KEY_URL="https://dl.sinew.in/keys/enpass-linux.key"
    APT_LIST_NAME="enpass"
    APT_REPO_URL="deb http://repo.sinew.in/ stable main"
    PRETTY_NAME="Enpass"
    WEBSITE="https://www.enpass.io/"
}

function deb_microsoft-edge-stable() {
    APT_KEY_URL="https://packages.microsoft.com/keys/microsoft.asc"
    APT_LIST_NAME="microsoft-edge"
    APT_REPO_URL="deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
    PRETTY_NAME="Microsoft Edge"
    WEBSITE="https://www.microsoft.com/edge"
}

function deb_brave-browser() {
    APT_KEY_URL="https://brave-browser-apt-release.s3.brave.com/brave-core.asc"
    APT_LIST_NAME="brave-browser-release"
    APT_REPO_URL="deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    PRETTY_NAME="Brave"
    WEBSITE="https://brave.com/"
}

function deb_docker-ce() {
    ARCHS_SUPPORTED="amd64 arm64 armhf"
    APT_KEY_URL="https://download.docker.com/linux/ubuntu/gpg"
    APT_LIST_NAME="docker"
    APT_REPO_URL="deb [arch=${HOST_ARCH}] https://download.docker.com/linux/ubuntu ${UBUNTU_CODENAME} stable"
    PRETTY_NAME="Docker Engine"
    WEBSITE="https://www.docker.com/"
}

function deb_docker-desktop() {
    URL="$(curl -s "https://docs.docker.com/desktop/linux/" | grep -i main/amd64 | sed -e 's/<[^>]*>//g' | sed '/^[[:space:]]*$/d' | cut -d' ' -f8)"
    # FIXME: Find a way to derive the major version for Linux
    #local MAJOR_VER="$(curl -s "https://docs.docker.com/desktop/windows/release-notes/" | grep "#docker-desktop-" | sed -e 's/<[^>]*>//g' | head -n1 | sed -e 's/ //g' -e 's/DockerDesktop//')"
    local MAJOR_VER="4.8.0"
    VERSION_PUBLISHED="${MAJOR_VER}-$(echo "${URL}" | cut -d'/' -f7)"
    PRETTY_NAME="Docker Desktop"
    WEBSITE="https://www.docker.com/products/docker-desktop/"
}

function deb_irccloud-desktop() {
    get_github_releases "https://api.github.com/repos/irccloud/irccloud-desktop/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="IRCCloud Desktop"
    WEBSITE="https://www.irccloud.com/"
}

function deb_codium() {
    ARCHS_SUPPORTED="amd64 arm64 armhf"
    get_github_releases "https://api.github.com/repos/VSCodium/vscodium/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="VSCodium"
    WEBSITE="https://vscodium.com/"
}

function deb_micro() {
    get_github_releases "https://api.github.com/repos/zyedidia/micro/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="micro"
    WEBSITE="https://micro-editor.github.io/"
}

function deb_ludo() {
    ARCHS_SUPPORTED="amd64 armhf"
    get_github_releases "https://api.github.com/repos/libretro/ludo/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Ludo"
    WEBSITE="https://ludo.libretro.com/"
}

function deb_obsidian() {
    get_github_releases "https://api.github.com/repos/obsidianmd/obsidian-releases/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Obsidian"
    WEBSITE="https://obsidian.md/"
}

function deb_rambox() {
    get_github_releases "https://api.github.com/repos/ramboxapp/download/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*x64.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
    URL=$(grep "browser_download_url.*x64.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Rambox"
    WEBSITE="https://rambox.app/"
}

function deb_antimicrox() {
    get_github_releases "https://api.github.com/repos/AntiMicroX/antimicrox/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_CPU}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8)"
    URL=$(grep "browser_download_url.*${HOST_CPU}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="AntiMicroX"
    WEBSITE="https://antimicrox.github.io/"
}

function deb_franz() {
    get_github_releases "https://api.github.com/repos/meetfranz/franz/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Franz"
    WEBSITE="https://meetfranz.com/"
}

function deb_heroic() {
    get_github_releases "https://api.github.com/repos/Heroic-Games-Launcher/HeroicGamesLauncher/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v beta | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v beta | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="Heroic Games Launcher"
    WEBSITE="https://heroicgameslauncher.com/"
}

function deb_deb-get() {
    ARCHS_SUPPORTED="amd64 arm64 armhf i386"
    get_github_releases "https://api.github.com/repos/wimpysworld/deb-get/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL="$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="deb-get"
    WEBSITE="https://github.com/wimpysworld/deb-get"
}

function deb_skypeforlinux() {
    APT_KEY_URL="https://repo.skype.com/data/SKYPE-GPG-KEY"
    APT_LIST_NAME="skype-stable"
    APT_REPO_URL="deb [arch=amd64] https://repo.skype.com/deb stable main"
    PRETTY_NAME="Skype"
    WEBSITE="https://www.skype.com/"
}

function deb_wavebox() {
    APT_KEY_URL="https://wavebox.pro/dl/client/repo/archive.key"
    APT_LIST_NAME="wavebox-stable"
    APT_REPO_URL="deb [arch=amd64] https://download.wavebox.app/stable/linux/deb/ amd64/"
    PRETTY_NAME="Wavebox"
    WEBSITE="https://wavebox.io/"
}

function deb_wire-desktop() {
    APT_KEY_URL="https://wire-app.wire.com/linux/releases.key"
    APT_LIST_NAME="wire-desktop"
    APT_REPO_URL="deb [arch=amd64] https://wire-app.wire.com/linux/debian stable main"
    PRETTY_NAME="Wire"
    WEBSITE="https://wire.com/"
}

function deb_signal-desktop() {
    APT_KEY_URL="https://updates.signal.org/desktop/apt/keys.asc"
    APT_LIST_NAME="signal-xenial.list"
    APT_REPO_URL="deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    PRETTY_NAME="Signal"
    WEBSITE="https://signal.org/"
}

function deb_syncthing() {
    APT_KEY_URL="https://syncthing.net/release-key.txt"
    APT_LIST_NAME="syncthing"
    APT_REPO_URL="deb http://apt.syncthing.net/ syncthing release"
    PRETTY_NAME="Syncthing"
    WEBSITE="https://syncthing.net/"
}

function deb_sublime-text() {
    APT_KEY_URL="https://download.sublimetext.com/sublimehq-pub.gpg"
    APT_LIST_NAME="sublime-text"
    APT_REPO_URL="deb https://download.sublimetext.com/ apt/stable/"
    PRETTY_NAME="Sublime Text"
    WEBSITE="https://www.sublimetext.com/"
}

function deb_plexmediaserver() {
    ARCHS_SUPPORTED="amd64 arm64 armhf i386"
    APT_KEY_URL="https://downloads.plex.tv/plex-keys/PlexSign.key"
    APT_LIST_NAME="plexmediaserver"
    APT_REPO_URL="deb https://downloads.plex.tv/repo/deb public main"
    PRETTY_NAME="Plex"
    WEBSITE="https://www.plex.tv/"
}

function deb_jellyfin() {
    ARCHS_SUPPORTED="amd64 arm64 armhf"
    APT_KEY_URL="https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key"
    APT_LIST_NAME="jellyfin"
    APT_REPO_URL="deb [arch=${HOST_ARCH}] https://repo.jellyfin.org/ubuntu ${UBUNTU_CODENAME} main"
    PRETTY_NAME="Jellyfin"
    WEBSITE="https://jellyfin.org/"
}

function deb_pandoc() {
    ARCHS_SUPPORTED="amd64 arm64"
    get_github_releases "https://api.github.com/repos/jgm/pandoc/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | head -n1 | cut -d'"' -f4 | cut -d'-' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Pandoc"
    WEBSITE="https://pandoc.org/"
}
function deb_sublime-merge() {
    APT_KEY_URL="https://download.sublimetext.com/sublimehq-pub.gpg"
    APT_LIST_NAME="sublime-text"
    APT_REPO_URL="deb https://download.sublimetext.com/ apt/stable/"
    PRETTY_NAME="Sublime Merge"
    WEBSITE="https://www.sublimemerge.com/"
}

function deb_google-earth-pro-stable() {
    APT_KEY_URL="https://dl-ssl.google.com/linux/linux_signing_key.pub"
    APT_LIST_NAME="google-earth-pro"
    APT_REPO_URL="deb [arch=amd64] http://dl.google.com/linux/earth/deb/ stable main"
    PRETTY_NAME="Google Earth Pro"
    WEBSITE="https://www.google.com/earth/versions/"
}

function deb_balena-etcher-electron() {
    ARCHS_SUPPORTED="amd64 i386"
    get_github_releases "https://api.github.com/repos/balena-io/etcher/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Etcher"
    WEBSITE="https://www.balena.io/etcher/"
}

function deb_figma-linux() {
    ARCHS_SUPPORTED="amd64 arm64"
    get_github_releases "https://api.github.com/repos/Figma-Linux/figma-linux/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Figma Linux"
    WEBSITE="https://github.com/Figma-Linux/figma-linux"
}

function deb_rpi-imager() {
    get_github_releases "https://api.github.com/repos/raspberrypi/rpi-imager/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL=$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)
    PRETTY_NAME="Raspberry Pi Imager"
    WEBSITE="https://github.com/raspberrypi/rpi-imager"
}

function deb_bitwarden() {
    get_github_releases "https://api.github.com/repos/bitwarden/desktop/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
    URL="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="Bitwarden"
    WEBSITE="https://bitwarden.com/"
}

function deb_insomnia() {
    get_github_releases "https://api.github.com/repos/Kong/insomnia/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | grep -v beta | head -n1 | cut -d'"' -f4 | cut -d'-' -f2 | sed s'|\.deb||')"
    URL="$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | grep -v beta | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="Insomnia"
    WEBSITE="https://insomnia.rest/"
}

function deb_onlyoffice-desktopeditors() {
    get_github_releases "https://api.github.com/repos/ONLYOFFICE/DesktopEditors/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8 | sed 's|v||')"
    URL="$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="ONLYOFFICE Desktop Editors"
    WEBSITE="https://www.onlyoffice.com/en/desktop.aspx"
}

function deb_powershell() {
    get_github_releases "https://api.github.com/repos/PowerShell/PowerShell/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v -e preview -e lts | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL="$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | grep -v -e preview -e lts | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="PowerShell"
    WEBSITE="https://docs.microsoft.com/powershell/"
}

function deb_mailspring() {
    get_github_releases "https://api.github.com/repos/Foundry376/Mailspring/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8)"
    URL="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="Mailspring"
    WEBSITE="https://getmailspring.com/"
}

function deb_mattermost-desktop() {
    get_github_releases "https://api.github.com/repos/mattermost/desktop/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'/' -f8)"
    URL="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="Mattermost Desktop"
    WEBSITE="https://mattermost.com/"
}

function deb_syft() {
    ARCHS_SUPPORTED="amd64 arm64"
    get_github_releases "https://api.github.com/repos/anchore/syft/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v -e preview -e lts | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="Syft"
    WEBSITE="https://github.com/anchore/syft"
}

function deb_grype() {
    ARCHS_SUPPORTED="amd64 arm64"
    get_github_releases "https://api.github.com/repos/anchore/grype/releases"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | grep -v -e preview -e lts | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="Grype"
    WEBSITE="https://github.com/anchore/grype"
}

function deb_trivy() {
    ARCHS_SUPPORTED="amd64 arm64 armhf i386"
    get_github_releases "https://api.github.com/repos/aquasecurity/trivy/releases"
    case ${HOST_ARCH} in
        amd64)
            VERSION_PUBLISHED="$(grep "browser_download_url.*64bit.deb" "${CACHE_DIR}/${APP}.json" | grep -v -e preview -e lts | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
            URL="$(grep "browser_download_url.*64bit.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
            ;;
        arm64)
            VERSION_PUBLISHED="$(grep "browser_download_url.*ARM64.deb" "${CACHE_DIR}/${APP}.json" | grep -v -e preview -e lts | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
            URL="$(grep "browser_download_url.*ARM64.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
            ;;
        armhf)
            VERSION_PUBLISHED="$(grep "browser_download_url.*ARM.deb" "${CACHE_DIR}/${APP}.json" | grep -v -e preview -e lts | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
            URL="$(grep "browser_download_url.*ARM.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
            ;;
        i386)
            VERSION_PUBLISHED="$(grep "browser_download_url.*32bit.deb" "${CACHE_DIR}/${APP}.json" | grep -v -e preview -e lts | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
            URL="$(grep "browser_download_url.*32bit.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
            ;;
    esac
    PRETTY_NAME="Trivy"
    WEBSITE="https://aquasecurity.github.io/trivy/"
}

function deb_gitter() {
    VERSION_PUBLISHED="$(curl -s "https://gitlab.com/gitterHQ/desktop/-/raw/master/CHANGELOG.md" | head -n1 | cut -d'`' -f2)"
    case ${HOST_ARCH} in
        amd64) URL="https://update.gitter.im/linux64/gitter_${VERSION_PUBLISHED}_${HOST_ARCH}.deb";;
        i386) URL="https://update.gitter.im/linux32/gitter_${VERSION_PUBLISHED}_${HOST_ARCH}.deb";;
    esac
    PRETTY_NAME="Gitter"
    WEBSITE="https://gitter.im/"
}

function deb_slack-desktop() {
    APT_KEY_URL="https://packagecloud.io/slacktechnologies/slack/gpgkey"
    APT_LIST_NAME="slack"
    APT_REPO_URL="deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"
    PRETTY_NAME="Slack"
    WEBSITE="https://slack.com/"
}

function deb_vivaldi-stable() {
    ARCHS_SUPPORTED="amd64 arm64 armhf"
    APT_KEY_URL="http://repo.vivaldi.com/stable/linux_signing_key.pub"
    APT_LIST_NAME="vivaldi"
    APT_REPO_URL="deb [arch=${HOST_ARCH}] https://repo.vivaldi.com/stable/deb/ stable main"
    PRETTY_NAME="Vivaldi"
    WEBSITE="https://vivaldi.com/"
}

function deb_gitkraken() {
    VERSION_PUBLISHED="$(curl -s "https://www.gitkraken.com/download/linux-deb" | grep "name: '" | cut -d"'" -f2)"
    URL="https://release.gitkraken.com/linux/gitkraken-amd64.deb"
    PRETTY_NAME="GitKraken"
    WEBSITE="https://www.gitkraken.com/invite/ieih1QR3"
}

function deb_webex() {
    # Note: get version number from Release Notes
    VERSION_PUBLISHED="$(curl -s "https://help.webex.com/en-us/article/mqkve8/Webex-App-%7C-Release-notes" | grep "<p class=\"p\">Linux—" | head -n1 | cut -d'>' -f2 | cut -d'<' -f1 | sed 's/Linux—//')"
    URL="https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb"
    PRETTY_NAME="Webex"
    WEBSITE="https://www.webex.com/"
}

function deb_dropbox() {
    ARCHS_SUPPORTED="amd64 i386"
    URL="https://linux.dropbox.com/packages/ubuntu/$(curl -s "https://linux.dropbox.com/packages/ubuntu/" | grep "${HOST_ARCH}.deb" | sed -e 's/<[^>]*>//g' | grep -v nautilus | cut -d' ' -f1 | tail -n1)"
    VERSION_PUBLISHED="$(echo "${URL}" | cut -d'_' -f2)"
    PRETTY_NAME="Dropbox"
    WEBSITE="https://www.dropbox.com/"
}

function deb_spotify-client() {
    # NOTE: Using direct as the latest spotify-client .deb is not in the archive Packages index.
    local VERSION_UPSTREAM="$(curl -s http://repository.spotify.com/pool/non-free/s/spotify-client/ | sed -e 's/<[^>]*>//g' | sed '/^[[:space:]]*$/d' | grep -v Index | cut -d'_' -f2 | sort -uVr | head -n1)"
    VERSION_PUBLISHED="1:${VERSION_UPSTREAM}"
    URL="http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_${VERSION_UPSTREAM}_amd64.deb"
    PRETTY_NAME="Spotify"
    WEBSITE="https://www.spotify.com/"
}

function deb_keybase() {
    ARCHS_SUPPORTED="amd64 i386"
    APT_KEY_URL="https://keybase.io/docs/server_security/code_signing_key.asc"
    APT_LIST_NAME="keybase"
    APT_REPO_URL="deb http://prerelease.keybase.io/deb stable main"
    PRETTY_NAME="Keybase"
    WEBSITE="https://keybase.io/"
}

function deb_zoom() {
    URL=$(unroll_url "https://zoom.us/client/latest/zoom_amd64.deb")
    VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f5)"
    PRETTY_NAME="Zoom"
    WEBSITE="https://zoom.us/"
}

function deb_exodus() {
    VERSION_PUBLISHED="$(curl -s https://www.exodus.com/download/|sed "s/.*https:\/\/downloads.exodus.com\/releases\/hashes-exodus-//"|sed "s/\.txt.*//")"
    URL="https://downloads.exodus.com/releases/exodus-linux-x64-${VERSION_PUBLISHED}.deb"
    PRETTY_NAME="Exodus"
    WEBSITE="https://exodus.com/"
}

function deb_jabref() {
    get_github_releases "https://api.github.com/repos/jabref/jabref/releases/latest"
    VERSION_PUBLISHED="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4 | cut -d'_' -f2)"
    URL="$(grep "browser_download_url.*${HOST_ARCH}.deb" "${CACHE_DIR}/${APP}.json" | head -n1 | cut -d'"' -f4)"
    PRETTY_NAME="JabRef"
    WEBSITE="https://www.jabref.org/"
}

# Create an array of all the deb_ functions
readonly APPS=($(declare -F | grep deb_ | sed 's|declare -f deb_||g' | sort))
export CACHE_DIR="/var/cache/deb-get"
if [ -d /var/cache/get-deb ]; then
    mv /var/cache/get-deb "${CACHE_DIR}"
fi
mkdir -p "${CACHE_DIR}" 2>/dev/null
chmod 755 "${CACHE_DIR}" 2>/dev/null
export VERSION="0.2.2"

if ((BASH_VERSINFO[0] < 4)); then
    fancy_message fatal "Sorry, you need bash 4.0 or newer to run $(basename ${0})."
fi

if [ "$(id -u)" -ne 0 ]; then
  fancy_message fatal "You must use sudo to run $(basename ${0})."
fi

if [ -z "${SUDO_USER}" ]; then
  fancy_message fatal "You must use sudo to run $(basename ${0})."
else
  SUDO_HOME=$(getent passwd "${SUDO_USER}" | cut -d: -f6)
fi

if ! command -v lsb_release 1>/dev/null; then
  fancy_message fatal "lsb_release not detected. Quitting."
fi

export HOST_CPU="$(uname -m)"
case ${HOST_CPU} in
  aarch64|armv7l|x86_64) export HOST_ARCH="$(dpkg --print-architecture)";;
  *) fancy_message fatal "${HOST_CPU} is not supported. Quitting.";;
esac

readonly USER_AGENT="Mozilla/5.0 (X11; Linux ${HOST_CPU}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"

OS_ID=$(lsb_release --id --short)
case "${OS_ID}" in
  Elementary) OS_ID_PRETTY="elementary OS";;
  Linuxmint) OS_ID_PRETTY="Linux Mint";;
  Neon) OS_ID_PRETTY="KDE Neon";;
  Pop) OS_ID_PRETTY="Pop!_OS";;
  Ubuntu) OS_ID_PRETTY="Ubuntu";;
  Zorin) OS_ID_PRETTY="Zorin OS";;
  *) fancy_message fatal "${OS_ID} is not supported.";;
esac

OS_CODENAME=$(lsb_release --codename --short)
if [ -e /etc/os-release ]; then
    UBUNTU_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2)
else
    fancy_message fatal "/etc/os-release not found. Quitting"
fi

case "${UBUNTU_CODENAME}" in
    focal)  UBUNTU_RELEASE=20.04;;
    impish) UBUNTU_RELEASE=21.10;;
    jammy)  UBUNTU_RELEASE=22.04;;
    *) fancy_message fatal "${OS_ID_PRETTY} ${OS_CODENAME^} is not supported because it is not derived from a supported Ubuntu release.";;
esac

if [ -n "${1}" ]; then
    ACTION="${1,,}"
else
    fancy_message error "You must specify an action."
    usage
fi

if [ "${ACTION}" == "install" ] || [ "${ACTION}" == "reinstall" ] || [ "${ACTION}" == "remove" ] || [ "${ACTION}" == "purge" ] || [ "${ACTION}" == "show" ] || [ "${ACTION}" == "search" ]; then
    if [ -n "${2}" ]; then
        APP="${2,,}"
    else
        fancy_message error "You must specify an app:\n"
        list_debs
        exit 1
    fi

    if [ "${ACTION}" != "search" ]; then
        # Check this app is supported and initialise the variables
        validate_deb "${APP}"
    fi
fi

case "${ACTION}" in
    cache) ls -lh "${CACHE_DIR}/";;
    clean) rm -v "${CACHE_DIR}"/*.deb;;
    show) info_deb;;
    install|reinstall)
        if [[ "${ARCHS_SUPPORTED}" != *"${HOST_ARCH}"* ]]; then
            fancy_message error "${APP} is not supported on ${HOST_ARCH}."
            return
        fi
        case ${METHOD} in
            direct|github|website) install_deb "${URL}";;
            apt) install_apt;;
            ppa) install_ppa;;
        esac
        ;;
    list) list_debs;;
    pretty_list|prettylist) prettylist_debs;;
    purge) remove_deb "${APP}" purge;;
    remove) remove_deb "${APP}";;
    search) list_debs | grep "${APP}";;
    update) update_debs;;
    upgrade) upgrade_debs;;
    version) echo "${VERSION}";;
    help) usage;;
    *) fancy_message fatal "Unknown action supplied: ${ACTION}";;
esac
