blank_issues_enabled: false
contact_links:
  - name: Wimpy's World Discord
    url: https://wimpysworld.io/discord
    about: If you're not sure what to do, or have a general question about `deb-get`, then ask in Wimpy's World Discord
